# Generated by Django 3.0.5 on 2020-07-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_orderproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproduct',
            name='ammount',
            field=models.IntegerField(default=0),
        ),
    ]
